name: OIDC Smoke Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  assume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::422017356225:role/ai-twin-devops-dev
          aws-region: us-east-2

      - name: Who am I
        run: aws sts get-caller-identity
